### tambah jenis-surat
GET http://localhost:7000/api/v1/surat-keluar/create
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsdW1lbi1qd3QiLCJzdWIiOnsiaWQiOiIyMTA2MjAyMjA0MzE2MzU4MSIsImtkaiI6Ii0ifSwiaWF0IjoxNjI0MjAxNDgxfQ.DQT-W7ikbw32lo-hx4MhQRtiy3ZsIepsfPDT8dQZZJ8


### validasi surat
PUT http://localhost:7000/api/v1/surat-keluar/validasi-surat
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsdW1lbi1qd3QiLCJzdWIiOnsiaWQiOiIxOTgwMTIxMDIwMDYwNDIwMTgiLCJrZGoiOiIwNS4wMS4wMi4wMS4ifSwiaWF0IjoxNjI1NDk1OTg3fQ.pwTJFHZbN2b1mslpaFQHW-8fFrqFDvXjq0kksH191TE

{
    "id_surat_keluar": "1",
    "kode_jabatan_terusan": "01.01.",
    "ket": "Disetujui",
    "catatan": ""
}

### get data atasan
GET http://localhost:7000/api/v1/surat-keluar/get-atasan
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsdW1lbi1qd3QiLCJzdWIiOnsiaWQiOiIxOTgwMTIxMDIwMDYwNDIwMTgiLCJrZGoiOiIwNS4wMS4wMi4wMS4ifSwiaWF0IjoxNjI1NDk1OTg3fQ.pwTJFHZbN2b1mslpaFQHW-8fFrqFDvXjq0kksH191TE

